# Generated by Django 6.0.3 on 2026-03-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=200, unique=True)),
                ('species', models.CharField(blank=True, max_length=200)),
                ('division', models.CharField(blank=True, max_length=50)),
                ('ploidy', models.CharField(blank=True, max_length=50)),
                ('number_of_lir', models.IntegerField(blank=True, null=True)),
                ('genome_length', models.CharField(blank=True, max_length=100)),
                ('table_file', models.CharField(blank=True, max_length=500)),
                ('fasta_file', models.CharField(blank=True, max_length=500)),
                ('irf_json_file', models.CharField(blank=True, max_length=500)),
                ('spark_json_file', models.CharField(blank=True, max_length=500)),
                ('gene_overlap_file', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
