# Generated by Django 6.0.3 on 2026-03-23 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChromSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('division', models.CharField(blank=True, max_length=50)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chrom_sizes', to='lir.species')),
            ],
            options={
                'unique_together': {('species', 'chrom')},
            },
        ),
    ]
