# Generated by Django 6.0.3 on 2026-03-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lir', '0002_chromsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='blast_db',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
