from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.conf import settings
from .models import Species
from .services.loaders import (
    load_lir_table,
    load_gene_overlap,
    load_fasta_as_dict,
    load_irf_json,
)
import logging
logger = logging.getLogger(__name__)
import json
import csv
from django.http import HttpResponse
from .services.loaders import load_spark_summary
from .services.blast import run_blastn
from django.conf import settings
from .services.annotate import run_irf
import os
import tempfile
import subprocess
import glob
import re
from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponseRedirect


def home(request):
    return render(request, 'lir/home.html')


def species_list(request, division):
    species_qs = Species.objects.filter(division=division).order_by('accession')
    return render(request, 'lir/species_list.html', {
        'division': division,
        'species_list': species_qs,
    })

def species_detail(request, accession):
    sp = get_object_or_404(Species, accession=accession)

    lir_rows_page = None
    error_message = None
    page_number = request.GET.get("page", 1)

    try:
        df = load_lir_table(sp.table_file)
        lir_rows = df.to_dict(orient="records")

        paginator = Paginator(lir_rows, 100)   # 每页100条
        lir_rows_page = paginator.get_page(page_number)

    except Exception as e:
        error_message = str(e)

    return render(request, 'lir/species_detail.html', {
        'species': sp,
        'lir_rows_page': lir_rows_page,
        'error_message': error_message,
    })

    
def lir_detail(request, accession, lir_id):
    sp = get_object_or_404(Species, accession=accession)

    lir_row = None
    error_message = None
    sequence = ""
    overlap_rows = []
    align_text = ""

    try:
        # 1. 主表里找该 LIR
        df = load_lir_table(sp.table_file)
        matched = df[df["ID"] == lir_id]

        if not matched.empty:
            lir_row = matched.iloc[0].to_dict()
        else:
            error_message = f"没有找到对应的 LIR：{lir_id}"

        # 2. fasta 序列
        if sp.fasta_file:
            fasta_dict = load_fasta_as_dict(sp.fasta_file)
            sequence = fasta_dict.get(lir_id, "")

        # 3. 基因重叠
        if sp.gene_overlap_file:
            op_df = load_gene_overlap(sp.gene_overlap_file)
            if "ID" in op_df.columns:
                op_df = op_df[op_df["ID"] == lir_id]
                overlap_rows = op_df.to_dict(orient="records")

        # 4. IRF alignment
        if sp.irf_json_file:
            irf_data = load_irf_json(sp.irf_json_file)

            if "LIR_align" in irf_data:
                raw_align = irf_data["LIR_align"].get(lir_id, "")

                if isinstance(raw_align, list):
                    align_text = "\n".join([str(x) for x in raw_align])
                else:
                    align_text = str(raw_align)

    except Exception as e:
        error_message = str(e)

    return render(request, 'lir/lir_detail.html', {
        'species': sp,
        'lir_id': lir_id,
        'lir_row': lir_row,
        'sequence': sequence,
        'overlap_rows': overlap_rows,
        'align_text': align_text,
        'error_message': error_message,
    })
def search_by_region(request):
    species_list = Species.objects.all().order_by("accession")

    selected_accession = request.GET.get("accession", "").strip()
    selected_chr = request.GET.get("chrom", "").strip()
    start = request.GET.get("start", "").strip()
    end = request.GET.get("end", "").strip()
    page_number = request.GET.get("page", 1)  # 页码

    chrom_list = []
    chrom_max = None
    results_page = None
    error_message = None

    try:
        if selected_accession:
            sp = get_object_or_404(Species, accession=selected_accession)
            chrom_list = list(sp.chrom_sizes.all().order_by("chrom"))

            if selected_chr:
                chrom_obj = sp.chrom_sizes.filter(chrom=selected_chr).first()
                if chrom_obj:
                    chrom_max = chrom_obj.size

            if selected_chr and chrom_max and not end:
                end = str(chrom_max)

            # 执行搜索
            if selected_chr and start and end:
                start_i = int(start)
                end_i = int(end)

                if start_i > end_i:
                    error_message = "start 不能大于 end"
                elif chrom_max is not None and (start_i < 1 or end_i > chrom_max):
                    error_message = f"范围超出染色体最大长度：{chrom_max}"
                else:
                    df = load_lir_table(sp.table_file)
                    matched_df = df[
                        (df["chr"] == selected_chr) &
                        (df["Left_start"] <= end_i) &
                        (df["Right_end"] >= start_i)
                    ]

                    results = matched_df.to_dict(orient="records")

                    # ====================== ✅ 分页 ======================
                    paginator = Paginator(results, 100)  # 每页100条
                    results_page = paginator.get_page(page_number)

    except Exception as e:
        error_message = str(e)

    return render(request, "lir/search_region.html", {
        "species_list": species_list,
        "selected_accession": selected_accession,
        "selected_chr": selected_chr,
        "start": start if start else "1",
        "end": end,
        "chrom_list": chrom_list,
        "chrom_max": chrom_max,
        "results_page": results_page,  # ✅ 传给模板的是分页对象
        "error_message": error_message,
    })


def search_by_id(request):
    species_list = Species.objects.all().order_by("accession")

    results_page = None
    error_message = None

    selected_accession = request.GET.get("accession", "").strip()
    query_text = request.GET.get("lir_ids", "").strip()
    page_number = request.GET.get("page", 1)
    action = request.GET.get("action", "").strip()

    example_ids = """Chr01:264866--266342,268784--270268
Chr01:268559--270290,271818--273518
Chr01:267346--267841,274817--275366
"""

    if action == "example":
        selected_accession = "A1_Mutema_genome_WHU_v1.1"
        query_text = example_ids

    elif action == "reset":
        selected_accession = ""
        query_text = ""
        results_page = None

        return render(request, "lir/search_id.html", {
            "species_list": species_list,
            "results_page": results_page,
            "selected_accession": selected_accession,
            "query_text": query_text,
            "error_message": error_message,
        })

    try:
        if selected_accession and query_text:
            sp = get_object_or_404(Species, accession=selected_accession)
            df = load_lir_table(sp.table_file)

            ids = [x.strip() for x in query_text.splitlines() if x.strip()]
            matched_df = df[df["ID"].isin(ids)]

            results = matched_df.to_dict(orient="records")

            paginator = Paginator(results, 100)
            results_page = paginator.get_page(page_number)

    except Exception as e:
        error_message = str(e)

    return render(request, "lir/search_id.html", {
        "species_list": species_list,
        "results_page": results_page,
        "selected_accession": selected_accession,
        "query_text": query_text,
        "error_message": error_message,
    })


def search_blast(request):
    species_list = Species.objects.all().order_by("accession")

    results = []
    error_message = None

    selected_accession = "A1_Mutema_genome_WHU_v1.1"
    query_seq = ""
    evalue = "10"
    max_hits = "10"

    example_seq = """>example_query
CTTTTTTAGTTATAAGTGTTTTTTTTTTCTATTTGAAAATATCATACCAACAAATTAATATTGATAACAATTGAATTTGAATTTTAAAATCTGAAAAATATATGAACTAAATTTCTGAAAATAAGAGTAAAATAATTAAATTTCAAATATATGAAAATAAGGTATTACATATTTCAACTTAAAAATTTAAGCACTCAAAAAAATAAACATTGAAAATCGCTTTGATTAATCCCATTACAGGCTAAGCTGCACTGGATACCTATGAATGCAACCTTCCCAGGGACTATTACACGATGGCTTAACATTCTTGAGTGCCAACCAAACTGCACTGTTACATTTGAAACCGCTCCCGAAAGCGATTTGCCAAACCCGATCCCCCTTCCGCATCCGACCCTTCGCTTCCATATAGGCTAGCTCGTACCAGATCGAACTCGATGAGGTGTTACCGAACCGGTGAAGCGTCATACGAGAAGCTTCAACATGTACCGGAAGAAGATGCAAATTCTTCTCGAGCTCATCGATCACGGCTCTCCCACCGGCGTGTATACAAAAATGTTCAAACGCGAGCTTGAAATCCGGGATATAAGGCTTGATTTTAGCATTGATCAACTTGTTGGCAACTAATGTGACAAAGAACAAGATTTGTTCACTTATAGGAAGAACAAGGGGACCTAACGTAGTAATGTTGGACTTAAGTGCATTACCAGCAATCGTCATCAAATCTTTAGACAATGAAACACCTGTTTTCCCAACATCATCTTGTTCTTGTTGGACACAGTTAAACGCCTTATTATTAGCACCGCAATGTGTACGTACCACATGAATAAGTTTATACTTACTTCTTAGTTGGTCCACTGATTTATTCGATAATAAAACCGCAGCACCACCGATTCGAAACAAGCAATTTGGTAACAACATTGCTTTTTTGTTACCAAAATACCAATTTTGTGTAATATTTTCAGTACTAACAACAATGGCATAATTGTTCCGATGAACTTGTAACATATCTTTAGCTAAATCAACAGCTATAACACCAGCACTACATCCCATACCACCAAGATTAAAGCTTTTAATATTACCCCTCATCTTATACTTGTTGATAATCATTGAAGACAATGAAGGTGTTGGATTAAATAAACTACAATTAACGACAAGAATCCCAACATCTTTTGGCTTAACATTAGTGTTAGCAAAAAGGGTATCTAAAGCACCAAACATCACCTGTTCTGTCTCTTGTCTTGCAGCCTCCATTGATGGTTTTGGTGGAAGACAATGCATTGCTTCTGGTGCACATGTTTCTTCTCCAAGCCCTGACCTTCCCAAAATCTTGTCTAAAAACACCAAAGAGGTCTCATCAAAACAACCCATTAGCTTACAATGTTTCATGAACCGGTCGTGTTCCACTTTTAGCTTCGAAGGAGGGAGATAACAGGCATAATCCACCAAATAAACGGATCTTTTTCGGGTCATAAAGTAAACGATCGACCCGACCAAAACGAAAGCCGACAACACGACGACATAGACAAGGTTATGTTCAAGGTGAAGCCATGTTTGGTGGATGTCATTAAGGCTTAACCTCGATGCTTGAACGATGATAACAGCCATTAAAGGGACTAAACAAAGCTTTAAAAGGTGAGTTATGAGATAATGGTAACCAAGTTTAACGTACTTCAATTTAAGTACCCTATTGTTTGAACTGTTTTTTTCACCATTCATGGTGATGGGTGATTCAGAAAAAAGAAAAAAAAAACTGCGTTTTAATTTTTTTCTTGAAAAAGCTAAAAGATTTGATGGAAACTAGTTGGATTTTTTCGCTTGTTGTGAGCAAAAGGGGGTATATAACTATATATAATGGACAAAATTAAGAGTTTGTATTGAAAATTTTGTGGGTGTTTAAAGAGGGTTGATGAAGCATTTACAGCAAAGACCGGCCGCCATTAAAGAATACGTAGAGTGTTTGATGACTAATATTATTACCAGTTGAAATATACCGTAAGTGTCTATACTCTTCAACAATTTAAAATTTAGTCTCTTTATTTTTATTATAAAAAATTTAATCTTTTTACTTTTTATATTTAAAAATATAAATTCAACTGTTAATATAATTAAAATTATTATGTTAAATTCTTTCTCATTGTAACTTTGTTTTTCTTGTTATTTGGCTATCAAAATGAGTATTTAAATTAAAAAAGTAAGAAATTAAAATTTTCAAAATAAAAGTGAAAGAGCTAAAATAAAAATTTATAAAGAATACGTGTACTAATAATGTATTTTAACGTATATGTTTTAAAGAGCAATGATGAGAGGTTGGAGTTAGGGCGTTGGGCGTTGTGCGAATCTTCTTTGAGCTTTGGGTTTTCCTTTTGATGCATTTATGGAGTTCCATTGACAATTATGGACATTTACGGTCTAAGTAAAATTAGGTTCGAAGTGTGAAATGGTGAAAAGTATTCACGGTTGTATTATAAATCATAATAAATAAATTTGCGTTTCCTTTAATTTAATTTTTATATTTTAAAATTAAATTTAACAGTTGACCTTTTAAAAGAGTAAAATTAGTTTTTAATAAAAATATTAATTAAAATATTAATTTTTTAATGATAATGACATGACAATTCATATGAAAACTCTAATTTTTGAGAGACTAATTTTTGAGAGGCAATTATAAAATTTTTCTTAGAATTTTACTTAGTATTTTTCATTAAGCTGTTCATAATTTTTGAATAATTTAATTAATTCTTCATTTCTTTTCGAAATTCTCATTAAATATCTTAATTTTTTTAAATTTTAATTAAACCCTAAAATTTTTAAAATTTTCAATTAAGCATCCAAAACCTTTACTAGAGCTTACCTAACTTGATCCAACTTGTATCTCTATACAACTACCGTTGTTTCCCAAACAAAGCCATGCAATTGAGACTTGAGGTCCCTTCTATTTGACTCAAGGGCAGCGCTAGATTGGACCTTAAAATGGAAAAATTATGCTTCAGTCCTTCTAAAATTTAAAAATTATAAATTAATACATAATAAAATTACATTTTAACCTTTCATAAAATTATAAATTTTTTAATTTCATATCAAAAATTACTGAAAAAAATACATTTTACTTCTTATAAAAAATTATAATTTAAATTCGACTCCTACATCAAAAGCACACCACAATAAAAACATGCATGCATCTTCCTAACTTTCGAAACCCAGAATACTCCCATTTCCTATCCCTTTCTCAGTATTCGTATGAACTTTCATTAACACAAACAATACCATACGTACACAAAGGCTAAAAGAACCACAAAAAAAAGGAAACACCCAACGCTCAACTCCCCACCCTCTCCATTATAACATACGACAATACTTGCAATTAAAACATTCTACGGGTTCTTCAATGGCTGCTATACTTACTGTATTTCATGCACATGAAAATATAATAACACATCTCATCATTAGGGGCAGAGGGATGCTTGCCTTTTCTCCTAAAAAATAAAAATTCTTTATATAGTCCCATTAGTTTTTAAGATATCACAAATTAATATGATGGTAAAATTGCATTCCCTTAATTTTTTTATTAATTTCTTGCCCCTAAAATAATTTCATTGCTTATTGTCAGTGAAGTAAAAAATAATAAATGAGTTATAAGTAAATATTAATAATTGTATTTTAAACATTAACAAATTCGAAACCTAAACTTGAGGGACAAATATAATATTTATGATTAATATATTTAATTATACTTAAATAAAATTATTAATATTTATTTATAAATTTTTCACCTACTAATGATAATGTTATTCATTGATGTTACATCACATGTTATTCCTTTGATCAATCATTTAGATCTTTCAAGGAAAATCATATACTTGACTCTTCGCGTCTGAGCTTTATATTTGAACAAGTTCTCACTTGTTCTTAAATGGCCGCCGGTAGTTATATGTATATACCATTGTTCATTATAAACGAAACCCAATTCACTTATCAATCTTTTAGAAAAACCAAGTTTCCTTTTTTACCCGACATCGTGAAAAATAGTTCAAAAATGGAGTTCAGGTCCTGCAACCAAGGAGATTGCCTGATTTCTTACGTAGTGTCAAATTAAAGTACATTAATTTCACAAAAAAAAAAATTTTAAGTACGTTGAACTTGGTTATCATTATCTCATAAGTCATCTTTTGAAACTTTGTTTGTTCCCTGTAATGGCGGCTGTTACCATTCAAGCATCGAGGTTAAGCCTTGATGACATCCACCAAATGTGGCTTCAGCTTGAATATAACCTCGTCAGCGTCGTCGTTTTCTCTGCTATCTTTGTCTTCGGGTCGACCGTTTATGTTATGACACGAAAAAGATCCATTTAATTGTTGGATTACGCTTGTAACCTCCCTCCACAACACCTCAAAGCCGATCACCGGTATTTCATTTAATATGCCAAGGAGGCGGCCGATTTCGATGAGTCCACTATGGAGTTTTTACGTAAGATTATGGAAAGGTCAGGGCTCGGAGACGAAATCGGCGCGCCGCCATCACTGCATTGCTTTCCCCCACGACCGTCTATGGTGGTGAAAGAGAAGAAGCAGAACTGGTGATGTTTGGTGCTTTAGATACCCCTTTTGCTAACATTAATGTTGAGCCAAGGGATGTCGGGATTCTTGTCGTTAATTGTAGTGTGTTTAATCCAACACCTTCATTAACGGCAATGATTATCAATAAGTATAAGATTAGGGCTAACATTAAGAGCTTTAATCTTAGTGGTATGGGATGTAGTGCTGGTGTTATAGCCATTGGTCTCGCAAAAGACATGTTGCGAGTTCATCGGAACAATTACGCCGTTGTTTTTAGTACCGAAAACATGACACAGAATTGGTATTCCGGTACCGAGAAATCGATGTCGATATCGAATTGTCTGTTTAGACTTGGGGGTTCTGCGGTTTTGTTGTCGAATAAATCTGCAGACCGATGGAGGAGTAAGTACAAGCTTGTTAATGTGGTGAGGACTGAGGACACATTGTGGTGCTAATCACAAAGCATTTAAATGTATCCATTAAGAAGAAGATAATGTTGGGAAATTTTGGGTTTCATTGTCTAAAGATTTGATGGCAATTGCTGGTAATGCACTTAAGACCAACATCACTACATTGGGTCCCCTCGTTCTTCCTATAAGTGAAAAAATCTTGTTCTTTGTCACATTAGTTGCCAAGAAGTTGTTCAACGCCAAAACCAAGCCTTATGTTCCGGATTTCAAGCTCGCGTTCGAACATTTCTGTATCCATGCCGGAGGGAGGCGTGATCGATGAGCTCGAGAAGAATATGCAACTTTTCCAATTACATGTCGAGGCCTCTCGTATGACGCTCCACCGGTTCGGTAACACCTCGTCGTGTTCGATCTGAGCTGGCTTATATGGAGGCTAAGGGTCGGATGCGTAAAGGGGACCGTATTTGGCAAATCGCTTTCGGGAGCCGTTTCAAATGTAACAGTGCAGTTTGGTTGGTCCTCAAGAATGTTAAGCCGTCATGCCTCATGAAATAACCCTTGGGAAGATTGCGCTCACAAGTATCCAGTGAAGCTCAATCTGTAAAGGGATTAATAAGTAGCGAATGTTCGATGTTCATTTCAGTAGCGTAACGGTGTCGTTTATCTGAAAGGGTTTTTCACATAAAATTTGTGTGTGTTTTTTTTTCTTTACAATCATCCTATTACCATTACCGATATTTAATATAACATAAATAAAAAATTACAAAATGATGTTCAACTATTTAAGTTTTCCTTGATATAAAAGAATCTCTCTTTATTTTAATTATTAAATAAAAATTATATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGA
"""

    if request.method == "POST":
        action = request.POST.get("action", "blast")
        selected_accession = request.POST.get("accession", "").strip() or "A1_Mutema_genome_WHU_v1.1"
        query_seq = request.POST.get("sequence", "").strip()
        evalue = request.POST.get("evalue", "10").strip() or "10"
        max_hits = request.POST.get("max_hits", "10").strip() or "10"

        uploaded_file = request.FILES.get("fasta_file")

        if action == "load_example":
            selected_accession = "A1_Mutema_genome_WHU_v1.1"
            query_seq = example_seq
            evalue = "10"
            max_hits = "10"
            results = []

        elif action == "reset":
            selected_accession = "A1_Mutema_genome_WHU_v1.1"
            query_seq = ""
            evalue = "10"
            max_hits = "10"
            results = []

        elif action == "blast":
            try:
                sp = get_object_or_404(Species, accession=selected_accession)

                if not sp.blast_db:
                    error_message = "该物种还没有配置 BLAST 数据库路径"
                else:
                    # 优先使用上传文件内容
                    if uploaded_file:
                        file_content = uploaded_file.read().decode("utf-8", errors="ignore").strip()
                        query_to_use = file_content
                    else:
                        query_to_use = query_seq

                    results = run_blastn(
                        query_text=query_to_use,
                        db_path= settings.BASE_DIR / sp.blast_db,
                        evalue=evalue,
                        max_hits=max_hits,
                    )

            except Exception as e:
                error_message = str(e)

    return render(request, "lir/search_blast.html", {
        "species_list": species_list,
        "results": results,
        "error_message": error_message,
        "selected_accession": selected_accession,
        "query_seq": query_seq,
        "evalue": evalue,
        "max_hits": max_hits,
    })

def annotate_page(request):
    results = []
    fasta_map = {}
    align_map = {}
    error_message = None
    message = None

    debug_log = None
    debug_stderr = None
    debug_cmd = None
    debug_files = None
    debug_returncode = None
    warning_message = None

    fasta_text = ""
    match = "2"
    mismatch = "3"
    delta = "5"
    pm = "80"
    pi = "10"
    minscore = "40"
    maxlength = "100000"
    maxloop = "50000"
    flanklen = "200"

    example_fasta = """>test1
TTCGACGATTGCTTTGCTGTGTCGAGACATGAACATATTTGTCTGAACGCCATGCTATTTTCCTGTTAACGATGATTCAAGCAGTAACTAACTTGGTGTT
ATCCTTTTGTACTCTTCTATAATACGTTGTCATTGCCTCTTCAGTAAATTGCATTACATTCTCTATTTTCTGTGCAGTTCAACTAGTAGAGCTTGTCATT
TCGTGAACGTTGTACTGATTTGCCAGCACATGACCTTAATAAATTTGGTCCTAAGTTAGTCTTGGTACCAATTACCAATTATAAACATCACAGCTTGATA
TAAAAGAAAATGATGATTGCAGTGTCAAAAACTACAGCTCAGTCTGATGACCGTTTGCTCTGCTGAAAAGCAAAATTTAATACTGGGCATTAAGACAGCC
AACTGAACTAGTTCACACTTTATTTGACTAGTGTGTCTTATGTACATATGCTTCTTTTATCACAATCTGGAGCTAGTTGCATTAATCATCTTGTGTTTTT
GCTGCTTTACCATTTATTTTGGTGTAGTCGGCTACGGAGTCAAATGATGCAGAAGGCAAAGCAAGAGAGCGTAATGCAAAAGAAACAAGTGAATGTAATG
CAAGAGATTCCAGGTAAGCACAATTGAACAAGTTATCAGCATTTGGTTCTTTTCATCTGGTGTTTGATGAATTTTTGTGCTAAAACTTCATAGAAGAAAT
AATAAATTATTGGGTATTTAATTTTATATGAGAATATTATTTGTAGCACAATTTTACTGAATATATACGAGACGTGTCTATATGACATGTGGGTCCAGAA
ATTTTAAATATCACGGTGTCCGAATATATTCGATATTGGACTCGTTTTGTTGTATAATTTGAATAGAAAGTGATGGTTCAAATGGATTTTAAATCCGATA
TATGATTCAAAAGATTGGAACTATTAAAACAAAAGAAATACGCAAGTGCTATCGTTACTACGTGAGCATGCATGGTCATTGGCTGTGGTGATTAAACATA
TGGGGCCCACTGTCATTAGACATGTTAATCACATAATTATCTCCAGACTACAGTACACGTCGACGAATTGACTCGTCTCTGCGTCGGCTTATCACGAAGA
TTAGCACGGGGCGCTGGAAATTCGGAGGCCGTTTCCGTCGCCGCTGCCTATATAAGAAGCCGAACCCATCTAGAGCGGGGGACGCCGAGGACACCACAGG
AGACACCCATCTGCCCATTTTCATTCATCCCATTCTTCTCAGTAGATTAGGAAAATCAGGAGAGGAGATTGAAGCCGGCTGGTGATAGCAAACCGGCGCC
GCTGCGGAGAGAATTAAACACCGCAGCCGGCGTCCTTCATCAAGTCGAGTCATTTATCGACAACATGCCGCCAGAGCACATTGAATAAATATTAATTTTC
TAGATTAAACACAATAGATGTTCGGTCCTTATTGGCGATCGAAACATCTGCGTGTTTTTAATCTATCTTGATCTTGATGATTAAAGCCAGATCAATGAGG
GCCGAAGCACGGTTATCATCAAACTCCATTTATACAATCGATGGTATAAGGCTGGTTCGGTCCTCATTGGCGATCGGATTATCCGAACACTATTTGATAT
ATTTTCTATGCTCAAAACTAGATGTCCGGCCCTCATTGGAGATTGGATCATCTATTTGTTACTATGATATCGATAACAACGGCGCTAGATATGTCCAACT
TTCATTGGTGATTGGATAATCTAACCGATGTTTTACAAAATATATTTTGATACCATGCATACACATGGGAGCTATTCGTGATCTTTGGAAGTTAAAAATT
ATGGCCGAGTATTTACGAGGCCGGTGTCACGATATTATTAATATGTCCAAACATATAGGAACGTATACATGTTACTAGGTTCCGACGAGGCAAAAGTAAC
GATATATCCACATCTAATAAAGGCTGGCATATATGACTGGGCACCGACGAGGCAAAAGTCATCCCCTTTGTTATGATACCTGACTCATGTATGGACATGG
TGATAATATATTGTGACCACGTTTCGGCGAAACAAAGCCACCAATATATTGTCACCTATTGTGACCCTGTATTTTATTAATATCCCTATTTTCTGTGTGT
TCGTTGTTTTGTTTTCATCAAACAAAATAGGGAAACCCTGTATTTTATTAATCATGATTCATTAACATGAATGTTTACAAATACATGAGGGCTCCCGCAG
GAGTTCGCCTTTTGCCTTCGCGAGGAATACTTAATGGAAAGGTATGCGGACTGGAGATTGCGTCTAGTCCGCTGATTCCTGATGCCTAGCAATGAGGCGG
CCGGTTAATTACATCCACAGGAGCGAGCCTATGGAACACCTCCGATTAAGCTGTGTCATAAGTTGGTGTAGAGATTTAATGATAACTGTGATATAGGTGG
CTTTGTTTCGCTGAAACCTGGTCACAATATATTATTACCATGTTCATACATGAGTCAGGTATCATAACAAAGGGGATGACTTTTGCCTCGTCGGTGCCCA
GTCATATATGCCAGCCTTTATTAGATGTGGATATATCGTTACTTTTGCCTCGTCGGAACCTAGTAACATGTATCCGTTCCTATCTGTTTGGACATGTTAA
TAATATCGTGACACCGGCCTCGTAAATACTCGGCCATAATTTTTAACTTCCAAAGATCACGAATAGCTCCCATGTGTGTGCATGGTATCAAAATATATTT
TGTAAAACATCGGTTAGATTGTCCAATCACCAATGAAAGTTGGACATATCTAGCGCCGTTGTTATCGGTATCATACTAACAAATAGATGATCCAATCTCC
AATGAGGGCCGGACATCTAATTTTGAGCATAGAAAATATATCAAATAGTGTTCGGATAATCCGATCGCCAATGAGGACCGAACCAGCCTTATACCATCGA
TTGTATAAATGGAGTTTAATGATAACCGTGCTTCGGCTCTCATTGATCTGGCTTTAATCATCAAGATCAAGATAGATTAAAAACACGCAGATGTTCCGAT
CGCCAATAAGGACCGAACATCTATTGTGTTTAATCTAGAAAATTAATATTTATTCAATGTGCTCACCATCCAGCGCAAATATCCTGAATGGCGGCATGTT
GTCGATAAATGACTCGACTTGATGAAGGACGCCGGCTGCGGTGTTTAATTCTCTCCGCAGCGGCGCCGGTTTGCTATCACCGGCCGGCTTCAATCTCCTC
TCCTGATTTTCCTAATCTACTGAGAAGAATGGGATGAATGAAAATGGGCAGATGGGTGTCTCCTGTGGCGTCCTTGGCGTCCCCCGCTCTAGATGGGTTC
TACTTCTTATATAGGCAGCGGCGACGGAAACGGCCTCCGAATTTCTAGCGCCCCGTGCTAATCTTCGTGATAAGCCGACGCACAGACGAGCCAATCCGTC
GACGTGTACTGCAGTCTGGAGATAATTATGTGATTAACATGTCTAATGACAGTGGGCCCCATATGTTTAATCGCCACAGCCAATGACCATGCATGCTCAC
GTAGTAACGATAGCACTTGCTTATTTCTTTTGTTTTAATAGTTCTAATCTTTTGAATCGTATATCGGATTTAAAATCCATTTGAACCATCACTTTCTATT
CAATTATACAACAAAACGAGTCCAATATCGAATATATTCGGACACCATGATTTTTAAAATTTCTAGACCCACATGTCATATAGACACGTCTCGTATATAT
TCAGTAAAATTGTGCTAAAAATAATATTCTCATATAAAATTAAATGCCCAATAATTTATTATTTCTTCTATGAATTTTTAGCACAAAAATTCATCAAACA
AATGCCCCCCACCGAGTGTAGTTTGTACGCGAAGCAGGACAGACTTCACTAGGTGAAATACTCAGTAGTATATTGTTACGAAGGATTAATCCATCTCCGT
GTGGTACATGGCTTGATTCACAAGCTGGCTGCCAATCGGCAAATGACGTGCATGATCTGATATATACTGAAGCCGAGTTCATGTATCATACGGGCTCATG
GCCGTATGTCCTATATATATAAATAAAGTCTGTACAGCCTCTTAATCGAGTAATTAAAACAGAGCTCATGTTAGATCGTTAAAATCTTCGATCAGAGCTA
CTGCAAATTAACGGTGATCGACTGGGGAAAGCAGTCGATCGAATTTCTTTGCTACTGTTCAAGACAAGAAAATGCAGAAGGCTAGTGATCGTGCCGATCA
TACCAGCGTGTGCAACCCCACTTATACTTGGCAGGAGATCCCAGATGACCCACCATTGCCTGGCCATGATAGTGATGAAGGTATCAAGGAAACTTCCCAG
CAAGAGAGGGGCCTTGGCATGCAAAAATCTCACGGCGAAAAGATCATAATAAAAAAAGGGACAGAAGTTAGGTTCTGAATCGTTAAACTCTTCCGTGAAT
TGATCCATCTTATAAGTGCCTCTTTTTTTTAAAAGGGGAACCCCTATGTTGAGGCGCCCTCAATCTACACATTATACAGTGGACTAGCCAAGAAGGTGCC
AAGAGAAGATAATGGCGAGATGTTTCTTTGGTGTGATGACTTCAAATTTTTCTATCACATTGACCAGCAAAATATCTCACCCGAAGATGTAACGGCAATC
GGGACAGCGAAGAAGTGGATGTGTTTGTCTAAAGTAGCCTCTTGTTTGAACATCAAACAGGGCCACCGACTTATTTTTTCATGTGGATCATCACAGCTTC
CTCACAAGGAAACATAACATATCTATCATACCGCAAC
>test2
TGAGGCTTAAGCTGTCCGGAAGCATAAGCCACTACTTTTCCATCCTGCATGAGGACGCATCCTAGTCCTTTGCGGGATGCATCACAATAAATGATGAAGT
CCTGTTGAATATCGGGTAATGTCAGTACTGGGGCAGTGGTCAGTCTTCTTTTTAGTTCCTGGAAGCTTCTCTCACAAGCCTCAGTCCAAGTAAACTTCTT
CTCCTTCTTGAGTAGTTCCGTCATGGGTCGGGCTATCTTAGAGAATCCTTCAATGATAAGTCTCTGTCCTACACAAGGATAAATCTAGTAACTTAGAAGG
ATAAGTGGAGGTCCTGGTGAAGGACAACTCTTGTAAACTTAGAAGGATAATCTGGGTAACTAGACAAGGATAAATCTCCCAACCTACGGAAGGATAAGTC
TGTGTCCTACACAAGGATAAATCTAGTAACTTAGAAGGATAAGTGGAGGTCCTGGTGAAGGATAACTCTTGTAAACTTAGAAGGATAATCTGGGTAACTA
GACAAGGATAAATCTCCCAACCTATGGAAGGATAAGTCTGTGTCCTACACAAGGATAAATCTAGTAACTTAGAAGGATAAGTGGAGGTCCTGGTGAAGGA
TAACTCTTGTAAACTTAGAAGGATAATCTGGGTAACTAGACAAGGATAAATCTCCCAACCTACGGAAGGATAAGTCTGTGTCCTACAAAAGGATAAATCT
AGTAACTTAGAAGGATAAGTGGAGGTCCTGGTGAAGGATAACTCTTGTAAACTTAGAAGGATAATCTGGGTAACTAGACAAGGATAAATCTCCCAACCTA
CGGAAGGATAAGTCTGTGTCCTACACAAGGATAAATCTAGTAACTTAGAAGGATAAGTGGAGGTCCTGGTGAAGGACAACTCTTGTAAACTTAGAAGGAT
AATCTGGGTAACTAGGCAAGGATAAATCTCCCAACCTACAGAAGGATAAGTCTGTGTCCTACACAAGGATAAATCTAGTAACTTAGAAGGATAAGTGGAG
GTCCTGGTGAAGGATAACTCTTGTAAACTTAGAAGGATAATCTGGTTAACTAGACAAGGATAAATCTCCCAACCTACGGAAGGATAAGTCTGTGTCCTAC
ACAAGGATAAATGTAGTAACTTAGAAGGATAAGTGGAGGTCCTGGTGAAGGATAACTCTTGTAAACTTAGAAGGATAATTTGGGTAACTAGACAAGGATA
AATCTCCCAACCTACGGAAGGATAAGTCTGTGTCCTACACAAGGATAAATCTAGTAACTTAGAAGGATAAGTGGGAGTCCTCCTGAAAGATAATCGTAGT
AAATTTCCAACTATGACGAAGAAGGATAATTCGGGCCACTGCAGAAGGCTAAATCTAATAATCTACGCAAGGATAAGTCTGTGTGCTAGGAAAGGAATAA
GTGGGAGTCCTACAGAAGGATAAGTTGGAGTCGTACAGAAGGATAATTTCAATGACTGCAGAAGGATAAATATAGTAATCTTCCAACTCTGTCGACGAAG
GATAATTCGGGTCACTAAGGAAGGATAGATCTGCCAACCAACCCAAGGATAAGTCTGTGTCCTACAAAAGGATAAATCTAGTAACTTAGAAGGATAAGTA
GAGGTCCTCGTGAAGGATAAATCTTGTAAACTTAGAAGGATAATTTGGGTAACTAGACAAGGATAAATCTCCCAACCTACGAAAGGATAAGGCTGTGTCC
TACACAAGGATAAATCTGGTAAACTTAGAAGGATAAGTGGGAGTCCTCCTGAAACATAATCGTAGTGGGAGTCCCATCACCGTTCCTATTGACCAAGCGA
AAGTCGGTTTTGCCTCCTGAAACATAATCGTAGTGGATTTGCCTATCTCTGAATCAGAGATGCAGATGCTGGTAGCCCGGTTGTTTAGGGTTCTGGCCAT
AAACTTTCTGTTATCTTTCTAAACAATTTCACGCATTTTGTAATTTTCGTATACCAAGTTTTTTCTATCTATCGTTTAATAAAACTAGCGTCTAAGCTTT
TGGCGGGCTTAGAGCAAAACAGGCCAAAAAACAATGCAAAATGCTCTCAGCTCAGGTCTAGTTATCCTTGTTTGTTATCCTACATCCAACTTATCCGTCT
CAAGTTATCCTTCATCCAGTTATCCTTGTCTTCAGTTATCCGCATCCAGTTATCCTTGTCTGCCGTTATCCTTCACAAGCCCCAACAGCGATGATAAGTA
TATAAGCCATCACAGGTCGCATAATAGAGCTCACAAGGTCAGGTAATATAAGAACCAACAGCGATGATAATAATAAGTATATAAGCCATCACAAGTCGAA
TAATAGAGCCCACAGGTTCACGGTAGTATTTACCACAAATACCAACAGTTAACTGTACACATTGTTGGCAAAAAAGACCACAGTTCACATAGCAAAATAC
TAAGTGCTAAGATAGAAATTCATCTAGATAGCTATTCGAACAATGCTAAAATTCCATCAGGCACATCTGCAGTGTTTTCCTTGTGCTGGATAAGGCATGT
CAAAATCCCTCGACTGTAAGATTTAATGTATTGATCCCGCATCTGCAAATTGGAAAAAAAAACAGAGACAAATGAAGTTATAGACAGTATTTTCAGAACT
CCATAACAGGTTAAAAGGGAAGTTCCGTCACCAGACCTTTTCATCCCAAGTCAGCTTGTTGAGCACTCCTGCCACACCTATGAAATGTTCAAGAAAATAC
ATGGCTGCGAACACACTGTCATTGGGCTGTACACAAGACGGAAAAAATGACAGAGATTTTTCATCAAATGACACTGTTTTGTAGTTGCAGTCTCCTAAGA
CTTTGTTTAATTTCTTTCCCAAATCCAAAGCGAAATTTTTAATTTCGTCGCCACCGTTGTTGCAAAGAATACCGATCTGTTTCATATTCTTCAGTTGGAA
ACAGACCACAATCCATTCACCAGAGAATAAGACAGGGCAGTATATCTGCAAAAACAATGTGTATGTAACACATCTTGGTTTTTGGAAATTAACAGTTCCA
AAAAAAAAACATGTATTGATGCACAAACTTACAAATCGATGAGGAAACTCCACTGCTGATTTCTTTTCGTTGGATCCACCGAGTGCATCTTTAATCTTTT
TCTTCATACCTCCTTTGCCCTGCACTTAGGGGAAAATTAAGTACAAGATATTCTGTTATAGTTCTTAAATTTGCTGGGAAAGCAATGTTTTTTTACCTTG
TATAGTGGTGGGACAAAGATCCTGCTGTCATCAGGATACGTATTGTTCTCCAGGTATTTAATAAATAATGAGATAATATCCCCGGCACACTCAACTTTCT
GGAACGACTGTTCTATTTCAGAACCAGTCATTGCGATAGCTCCGAAATTCAATATTACTTGTTCCTTACTTTTCCAATTGGAAACATGACATCAGTATAG
CAAGTTTTACAGTTATATAATCATAAAGTTTCGAGATACATACCAATCAGTGGCAAGCTCATAAACCTCTTTAACTATCGCATCATCAGGCCACTCGCGT
CTAGTAGTCTTTATAGCAGTCCTGGTAGTTGCAATTCGGCACCTCTTGCCCAGTTGAATTAAGTCATTATCCAAGCTTGACCTGCTCTTCTCTTTCCTTT
TCTTCTCTTTCTTCTTTCTAGAATAATAAACTATGTCTTTATCGAGGGCATGGGATGGATTTTGTTCTCTGCGTGGTGGGGATGATGGCACCCCTTTTTC
ACCTTCATCCACCTTGTTGCCTCCAGCCTCATCATCGCTTGTCCTTGAGCGTTCATTGTCTGTTCTTGTATCCAGGGAACTTCCCTCACTGGATCTGTTG
GCCTTCCCTTGAGCTTGGGCATCGTCCACCTTCTGGTTACCATCGCTTGTCCTCGCATGATTCGCCTGGTTGCCTGCCTCAGCATTTTCTGCTATTCCCA
CACTGGATCTGTCAGCCTCCTCTTGGGGTTGGGCATCTTCCAGATTCTTGTTACCATCGCTTGTCCCTGGTGAGGATGGTGGCAGAGGGCCATCATTACG
CCCATCTTCATGACTCATGGGGGATACTGTCAGATTTGGGCGTGGAGGGGAATTTCGCAAATCTGAAGGGGGTGGTGACAAACATATGGTGTCGTCCAAA
ATGTGATATTCATCTTGAGCTATGACCTCGTCACTTACATCCTTAGGATTGTTGTTAGGATTCTCATATATGTCCTTCACAAGTTTTTTGCGATACATTA
ATACATCATTCTGCATTTTTTTGGGCATAAAAAAGGAACAAACATGAGTTATGAATTGTCTAGGACTTTTAAAAGTAGCCAAAACTGTTAGTTGAATAGT
TGAATAAAAGGCGTTACACTAACCTCATTGATGTCATCTATTTTCATTCTACCAAATCGTTCCATATACAGCAGCATATAGAATCCACAATCGGATATGC
AATAATCATTTGCATAGTTAAGAATTTCGATCATTGACCATTTAATGCAAGGGAACTGACAGCATCGGTTATAAGTGAAGGATAACCCAGCATAGGAAAA
CTTGACAACAGAATCATATGATAATTTCTAAGGTAATTTCATATGAAAATTATTAAGTGAGGAAAGATAAGCTCTAAGTGAAGATGAAGAATTACCCATT
CGTTTGGCTCTTAAGGTTTGGTGTTTTAGTGCTGAATGAAGAAAAATCAATATGTCCCCCCTTCGCAAAATATTTTTCCAACGCCGATAGCTGAAAGAAT
GCAATAAGGTGAGCTTCCATATGCACCCTTTGTAGAACATTTTATAAGTTGAAAAGTCATCCTCTTAATCTTACCACAGTTTCCGTCGCACTTCTAGTGC
CCCGTGATGGAAGGGAATCCAGTATATACCTTATTCCATTCTCAATGTCCACCACGAGCAAGTACCAATGTAAACCAGAACCATCCAAAGCTCGAACGAG
GATAGGGACAAATATCTGGAAAAAAATAAACTTTGTTTAATTCATGGCTTAATGCAAGAAACGAAACAGGATGGCAGAAAAGCACAAACCTGCTTCTTTT
TGGCTAGGTTAGACAACTCCTTTTCCACATAGCCTCTGATTTGGGTTAAACCCAACAGTTCATTCTGGACACAATAGAAGATATGGTGAACGTTGACAAT
ATAAAACATGTATAGACATTACATGTGCTTAAATTGATACTTACCACAGCAGATTGACTAAGGATTATTTTGTCTTTCCATTCTTCCTCCTCCCTCCATA
TGGAGCATTGCACGTCCACAATGAAGTTACTTATCCATCCATTCAGTTTCATGCTTTTTACAAAATCATGTTCTGAAATGGTAATGCCATTAATATCCAC
CGCAGCCTTATTGCCGAAATGTTTCTGTTCCCAATCGGCTTTTGACATAATGTGTTTTGAATAGAACTCATCCAAATCTTTATATCTGAAAAAAAACCAA
GCCTTTATTAAGAAAACTGTGTTATAGTAAAGGGGAAAAAACGAAAAGGATAATCCCTCACGGCATGCTTAGTCAGATTTGACCCATTCTCACTACTGCC
CCACACTTCATTCTTGCCAACCCAGACCCAGCCAACATACTCTCTCCAATCAGTCCCCCGATATGGCAAAGCTCTGGGAGGACCTATTCCTTATCCACTG
AAGAAACTAATCAAGACATGGCACTGGAGAGATGGAAGTGTGCTCGTGGGTTGAACAACAGAAATCAGAGAGGAGCCTAAAATGGTTTTGGAACTTTAAG
GACCAAATATAACTGGTATTGCTCATGAGAGACTAACCTGTCTACCAAGCTTTCCATTTTCGAGGGCATCTGTGACTGAGTCTTCATGATCTTCTCATAC
ATCTCTACAATCGACGAATGATTTTGCTTTACAATCTTGATAGCGTCGCTGTGCAGATAACGAGGCATGTGCTCTATAGAAGATTTAACAAAATCCTCTA
ATGCAGGAATGTGCGCAACCATGTCGTTCTTGGCACCACTGTCTTTCTCAGCTCTCTCACCATATCTTTTCACAACTTCCTTTCTTCTTACCGCGGGGTT
GACATGCGTGCCCTTTTCTTCTTTATCCCCTTTTTCGCCTTTGTTTTTGCCAAGACGAGTGCGCTTATTTTTCTGAAAAGGAGCAGGGATAGTGTATTCA
AGTGTATGTATTATATAGGAACAATGATATGTTGATTTTAGAACCAATATTCTTACATACTTTCTGCTTTCCAGACACTTTCTGCACCTTCACCTTCTCA
CATTCATTATAGCTTCTTGAATAACAGGTCTCTTCGGTTGTGCGAAACTGAAAATGGGGCATGGATTAAGTGTGTTTGACTGTAACATTACAGGAACAAT
GGCATAATGCTTAAAAATCAGATTCTTACCTTGAGGTTGTCAAACCTCTTGCCATCCTTTTGCATAGTTTCCTGCACCAAATCGGTCACCATAGATTCGC
CGTAGTAACAAATTCTTGGCGTCTGAGAGACATCGCTTTCGGATTTTGACTTTAGGAAGTCCAAGTAATATAACTGTAGGCATAAGTTTACCGTTAGATA
AATTTACTATTAATGATGAAAAAATAATGGTTTTAAAGATACTTACAAGAAGCACAGTCACAGGACCACTTATGTATACAGACGCGACACCACCAGGCTT
GGTTGATTTGGCACCAGGCTTGGTTGATTTGGCTTGCGATTTCCACCATGATTTAACACCATCTTTTAAATGGTTGAGAAGAACCTTGCGCCAATTAATT
CTTTGTATCCTTGCAAGGTTCATACCCGCTTGCATCTGGTGTAGAGTGAGATAACCATCCTTTTCTGGGAGCAGCAGTGTATGGAATGCGATGAAGAAGA
AGCACTTAACTTCCAGCTCAACATCTTTGGTCTCCTTGGCTTCTTCCATCACATCACGTAAATAATCAACGCCAATCTTGCCATTCATAATAGTTTTATG
TTTTCTATCCCTTTTCTTTTCATCTGCAATGGGCTCACAATCATCAACACTGTCAGGGAGCTTCAACAAATTGTGAACAGCTTTCTTGATTTCTCCTTGC
TTCTTAGTGTCCTGCTCAAATTCAAGGCTCTCACCAGAACCTTCAGGAACACCAACAACATGTGCCACCACATTCTCCGTGATGGGGGGTAACTTAGATC
CTTCAATCTTAATCTCAACACCTTCAGATGTTTGTTCTGTATGTGTATTGTTCATAAGAAACCTCAATATCTCTCTGTTACCAAAACCCTCTAAGGACAT
ATACAGTAACTGCTCAAAGCCTGCTGTTATAACCACGTTCCGTGCATCTGATGACAGTTCTTGAGCTGCTAAAATGACGCTGTTCGGACTGGACCGCGTA
TGAATCTTGGGATCCTTCATTTCAACCTATGCAGTAGAAGCCTCCCCCTCTTTGGTAGCATCAGCATCCCCCTCTTCAGTAGAAGCAGCCTCGTCTTCTT
TGATAGCATCAGCATCCCCCTCTTCAGTAGAAGCAGCCTCGCCCATATTTGCAACCTCTAAATTCACCTCCTCTCCAGATCCCTCCCTCCCAGAAGGGCC
CATTGATTCTCTGCACAATCCAAGATAAATGTCAAGACAGAAAGCAATAAGGATGAACTCGTGGATAAATGCATGAATACATGGATTTGAGTGACATTTG
TGTATCTATTCTATACATACGTGAATACATGGATTTGAGAAGCTCAACATAAGTCCTTGTGTTTGTGCCAGTTCCTATTCAGATGCAAGCAAGTACTGAC
CAGCCGCCACAGACGAAGGAACACCAGGGGAAGAATAAATAGATAAAGGATAAACAGACGCCTAGACCCTGAACCCTAAGCCCGGATAACCACAGACGAA
GGATAACTAGGGGAAGGATAAATAGATAAGGATAAACAGACGCCATCCCCGATTATCCTCACATCAGACGCCTAGACCCTAAACACATCAGAAAAAAGAT
AAACACACTCGAAGGATAAACCAAATCTTGACTTACCAAAGTGATCACAGTTTCCCGTGCGCTCGGGGAAGGAGAGCCGGAGGTAATCGTGGAGGAACGT
CGGGGCACGGAGCGTCGGGTGAGGATCGTCGGGTGAGGCTTCTGGCAAGAAGGTGAGGAAGCAAAGAGGTGAGGAAGCTTCGAAATTTTGGGTGGGGAAC
TGGCGGTTTTGTTTAAATGGAATCGGAATGGTTTTCTGTTTCGCAAAAAAAAACGACAATGTAAAAAAAACGCGTGTAAAAAAAAAGAACACTGCCGCAG
CCGAGGCCCGTGCCCTCGCCGGTGGCCATCGGCCTGCTGCGCCGCCGCAGCCGCGCGTCTGGCCAGCCCGCGCCGCAGGTGCCTAGCTGGCAGCCGCGCG
CCAACGCCGTAGCAGCCGCTCGCCTCGTTGCTCCCGTGCTGTGCTCTGCTCATGGCCTGACTTAGAATTTCGAAGCTTCCTCACCTCTTTGCTTCCTCAC
CTTCTTGCCAGAAGCCTCACCCGACGATCCTCACCCGACGCTCCGTGCCCCGATGTTCCTCCACGATTACCTCCGGCTCTCCTTCCCCGAGCGCACGGGA
AACTGTGATCACTTTGGTAAGTCAAGATTTGGTTTATCCTTCGACTGTGTTCATCCTTCGACTGTGTTTATCCTTTTTCTGATGTGTTTAGGGTCTAGGC
GTCTGATGTGAGGATAATCGGGGATGGCGTCTGTTTATCCTTATCTATTTATCCTTCCCCTAGTTATCCTTCGTCTGTGGTTATCCGGGCTTAGGGTTCA
GGGTCTAGGCGTCTGTTTATCCTTTATCTATTTATTCTTCCCCTGGTGTTCCTTCGTCTGTGGCGGCTGGTCAGTACTTGCTTGCATCTGAATAGGAACT
GGCACAAACACAAGGACTTATGTTGAGCTTCTCAAATCCATGTATTCACGTATGTATAGAATAGATACACAAATGTCACTCAAATCCATGTATTCATGCA
TTTATCCACGAGTTCATCCTTATTGCTTTCTGTCTTGACATTTATCTTGGATTGTGCAGAGAATCAATGGGCCCTTCTGGGAGGGAGGGATCTGGAGAGG
AGGTGAATTTAGAGGTTGCAAATATGGGCGAGGCTGCTTCTACTGAAGAGGGGGATGCTGATGCTATCAAAGAAGACGAGGCTGCTTCTACTGAAGAGGG
GGATGCTGATGCTACCAAAGAGGGGGAGGCTTCTACTGCATAGGTTGAAATGAAGGATCCCAAGATTCATACGCGGTCCAGTCCGAACAGCGTCATTTTA
GCAGCTCAAGAACTGTCATCAGATGCACGGAACGTGGTTATAACAGCAGGCTTTGAGCAGTTACTGTATATGTCCTTAGAGGGTTTTGGTAACAGAGAGA
TATTGAGGTTTCTTATGAACAATACACATACAGAACAAACATCTGAAGGTGTTGAGATTAAGATTGAAGGATCTAAGTTACCCCCCATCACGGAGAATGT
GGTGGCACATGTTGTTGGTGTTCCTGAAGGTTCTGGTGAGAGCCTTGAATTTGAGCAGGACACTAAGAAGCAAGGAGAAATCAAGAAAGCTGTTCACAAT
TTGTTGAAGCTCCCTGACAGTGTTGATGATTGTGAGCCCATTGCAGATGAAAAGAAAAGGGATAGAAAACATAAAACTATTATGAATGGCAAGATTGGCG
TTGATTATTTACGTGATGTGATGGAAGAAGCCAAGGAGACCAAAGATGTTGAGCTGGAAGTTAAGTGCTTCTTCTTCATCGCATTCCATACACTGCTGCT
CCCAGAAAAGGATGGTTATCTCACTCTACACCAGATGCAAGCGGGTATGAACCTTGCAAGGATACAAAGAATTAATTGGCGCAAGGTTCTTCTCAACCAT
TTAAAAGATGGTGTTAAATCATGGTGGAAATCGCAAGCCAAATCAACCAAGCCTGGTGCCAAATCAACCAAGCCTGGTGGTGTCGCGTCTGTATACATAA
GTGGTCCTGTGACTGTGCTTCTTGTAAGTATCTTTAAAACCATTATTTTTTCATCATTAATAGTAAATTTATCTAACGGTAAACTTATGCCTACAGTTAT
ATTACTTGGACTTCCTAAAGTCAAAATCCGAAAGCGATGTCTCTCAGACGCCAAGAATTTGTTACTACGGCGAATCTATGGTGACCGATTTGGTGCAGGA
AACTATGCAAAAGGATGGCAAGAGGTTTGACAACCTCAAGGTAAGAATCTGATTTTTAAGCATTATGCCATTGTTCCTGTAATGTTACAGTCAAACACAC
TTAATCCATGCCCCATTTTCAGTTTCGCACAACCGAAGAGACCTGTTATTCAAGAAGCTATAATGAATGTGAGAAGGTGAAGGTGCAGAAAGTGTCTGGA
AAGCAGAAAGTATGTAAGAATATTGGTTCTAAAATCAACATATCATTGTTCCTATATAATACATACACTTGAATACACTATCCCTGCTCCTTTTCAGAAA
AATAAGCGCACTCGTCTTGGCAAAAACAAAGGCGAAAAAGGGGATAAAGAAGAAAAGGGCACGCATGTCAACCCCGCGGTAAGAAGAAAGGAAGTTGTGA
AAAGATATGGTGAGAGAGCTGAGAAAGACAGTGGTGCCAAGAACGACATGGTTGCGCACATTCCTGCATTAGAGGATTTTGTTAAATCTTCTTTGGAGCA
CATGCCTCGTTATCTGCACAGCGACGCTATCAAGATTGTAAAGCAAAATCATTCGTCGATTGTAGAGATGTATGAGAAGATCATGAAGACTCAGTCACAG
ATGCCCTCGAAAATGGAAAGCTTGGTAGACAGGTTAGTCTCTCATGAGCAATACCAGTTATATTTGGTCCTTAAAGTTCCAAAACCATTTTAGGCTCCTC
TCTGATTTCTGTTGTTCAACCCACGAGCACACTTCCATCTCTCCAGTGCCATGTCTTGATTAGTTTCTTCAGTGGATAAGGAATAGGTCCTCCCAGAGCT
TTGCCATATCGGGGGACTGATTGGAGAGAGTATGTTGGCTGGGTCTGGGTTGGCAAGAATGAAGTGTGGGGCAGTAGTGAGAATGGGTCAAATCTGACTA
AGCATGCCGTGAGGGATTATCCTTTTCGTTTTTTCCCCTTTACTATAACACAGTTTTCTTAATAAAGGCTTGGTTTTTTTTCAGATATAAAGATTTGGAT
GAGTTCTATTCAAAACACATTATGTCAAAAGCCGATTGGGAACAGAAACATTTCGGCAATAAGGCTGCGGTGGATATTAATGGCATTACCATTTCAGAAC
ATGATTTTGTAAAAAGCATGAAACTGAATGGATGGATAAGTAACTTCATTGTGGACGTGCAATGCTCCATATGGAGGGAGGAGGAAGAATGGAAAGACAA
AATAATCCTTAGTCAATCTGCTGTGGTAAGTATCAATTTAAGCACATGTAATGTCTATACATGTTTTATATTGTCAACGTTCACCATATCTTCTATTGTG
TCCAGAATGAACTGTTGGGTTTAACCCAAATCAGAGGCTATGTGGAAAAGGAGTTGTCTAACCTAGCCAAAAAGAAGCAGGTTTGTGCTTTTCTGCCATC
CTGTTTCGTTTCTTGCATTAAGCCATGAATTAAACAAAGTTTATTTTTTTCCAGATATTTGTCCCTATCCTCGTTCGAGCTTTGGATGGTTCTGGTTTAC
ATTGGTACTTGCTCGTGGTGGACATTGAGAATGGAATAAGGTATATACTGGATTCCCTTCCATCACGGGGCACTAGAAGTGCGACGGAAACTGTGGTAAG
ATTAAGAGGATGACTTTTCAACTTATAAAATGTTCTACAAAGGGTGCATATGGAAGCTCACCTTATTGCATTCTTTCAGCTATCGGCGTTGGAAAAATAT
TTTGCGAAGGGGGGACATATTGATTTTTCTTCATTCAGCACTAAAACACCAAACCTTAAGAGCCAAACGAATGGGTAATTCTTCATCTTCACTTAGAGCT
TATCTTTCCTCACTTAATAATTTTCATATGAAATTACCTTAGAAATTATCATATGATTCTGTTGTCAAGTTTTCCTATGCTGGGTTATCCTTCACTTATA
ACCGATGCTGTCAGTTCCCTTGCATTAAATGGTCAATGATCGAAATTCTTAACTATGCAAATGATTATTGCATATCCGATTGTGGATTCTATATGCTGCT
GTATATGGAACGATTTGGTAGAATGAAAATAGATGACATCAATGAGGTTAGTGTAACGCCTTTTATTCAACTATTCAACTAACAGTTTTGGCTACTTTTA
AAAGTCCTAGACAATTCATAACTCATGTTTGTTCCTTTTTTATGCCCAAAAAAATGCAGAATGATGTATTAATGTATCGCAAAAAACTTGTGAAGGACAT
ATATGAGAATCCTAACAACAATCCTAAGGATGTAAGTGACGAGGTCATAGCTCAAGATGAATATCACATTTTGGACGACACCATATGTTTGTCACCACCC
CCTTCAGATTTGCGAAATTCCCCTCCACGCCCAAATCTGACAGTATCCCCCATGAGTCATGAAGATGGGCGTAATGATGGCCCTCTGCCACCATCCTCAC
CAGGGACAAGCGATGGTAACAAGAATCTGGAAGATGCCCAACCCCAAGAGGAGGCTGACAGATCCAGTGTGGGAATAGCAGAAAATGCCGAGGCAGGCAA
CCAGGCGAATCATGCGAGGACAAGCGATGGTAACCAGAAGGTGGACGATGCCCAAGCTCAAGGGAAGGCCAACAGATCCAGTGAGGGAAGTTCCCTGGAT
ACAAGAACAGACAATGAACGCTCAAGGACAAGCGATGATGAGGCTGGAGGCAACAAGGTGGATGAAGGTGAAAAAGGGGTGCCATCATCCCCACCACGCA
GAGAACAAAATCCATCCCATGCCCTCGATAAAGACATAGTTTATTATTCTAGAAAGAAGAAAGAGAAGAAAAGGAAAGAGAAGAGCAGGTCAAGCTTGTA
TAATGACTTAATTCAACTGGGCAAGAGGTGCCGAATTGCAACTACCAGGACTGCTATAAAGACTACTAGACGCGAGTGGCCTGATGATGCGATAGTTAAA
GAGGTTTATGAGCTTGCCACTGATTGGTATGTATCTCGAAACTTTATGATTATATAACTGTAAAACTTGCTATACTGATGTGTCATGTTTCCAATTGGAA
AAGTAAGGAACAAGTAATATTGAATTTCGGAGCTATCGCAATGACTGGTTCTGAAATAGAACAGTCGTTCCAGAAAGTCGAGTGTGCCGGGGATATTATC
TCATTATTTATTAAATACCTGGAGAACAATACGTATCCTGATGACAGCAGGATCTTTGTCCCACCAGTATACAAGGTAAAAAAACATTGCTTTCCCAGCA
AATTTAAGAACTATAACAGAATATCTTGTACTTAATTTTCCCCTAAGTGCAGGGCAAAGGAGGTATGAAGAAAAAGATTAAAGATGCACTCGGTGGATCC
AACGAAAAGAAATCAGCAGTGGAGTTTCCTCATCGATTTGTAAGTTTGTGCATCAATACATGTTTTTTTTTGGAACTGTTAATTTCCAAAAACCAAGATG
TGTTACATACACATTGTTTTTGCAGATATACTGCCCTGTCTTATTCTCTGGTGAATGGATTGTGGTCTGTTTCCAACTGAAGAATATGAAACAGATCGGT
ATTCTTTGCAACAACGGTGGCGACGAAATTAAAAATTTCGCTTTGGATTTGGGAAAGAAATTAAACAAAGTCTTAGGAGACTGCAACTACAAAACAGTGT
CATTTGATGAAAAATCTCTGTCATTTTTTCCGTCTTGTGTACAGCCCAATGACAGTGTGTTCGCAGCCATGTATTTTCTTGAACATTTCATAGGTGTGGC
AGGAGTGCTCAACAAGCTGACTTGGGATGAAAAGGTCTGGTGACGGAACTTCCCTTTTAACCTGTTATGGAGTTCTGAAAATACTGTCTATAACTTCATT
TGTCTCTGTTTTTTTTCCAATTTGCAGATGCGGGATCAATACATTAAATCTTACAGTCGAGGGATTTTGACATGCCTTATCCAGCACAAGGAAAACACTG
CAGATGTGCCTGATGGAATTTTAGCATTGTTCGAATAGCTATCTAGATGAATTTCTATCTTAGCACTTAGTATTTTGCTATGTGAACTGTGGTCTTTTTT
GCCAACAATGTGTACAGCTATTTAACTGTTGGTATTTGTGGTAAATACTACCGTGAACCTGTGGGCTCTATTATTCGACTTGTGATGGCTTATATACTTA
TTATTATCATCGCTGTTGGTTCTTATATTACCTGACCTTGTGAGCTCTATTATGCGACCTGTGATAGCTTATATACTTATCATCGCTGTTGGGGCTTGTG
AAGGATAACGGCAGACAAGGATAACTGGATGCGGATAACTGAAGACAAGGATAACTGGATGAAGGATAACTTGAGACGGATAAGTTGGATGTAGGATAAC
AAACAAGGATAACTAGACCTGAGCTGAGAGCATTTTGCATTGTTTTTTGGCCTGTTTTGCTCTAAGCCCGCCAAAAGCTTAGACGCTAGTTTTATTAAAC
GATAGATAGAAAAAACTTGGTATACGAAAATTACAAAATGCGTGAAATTGTTTAGAAAGATAACAGAAAGTTTATGGCCAGAACCCTAAACAACCGGGCT
ACCAGCATCTGCATCTCTGATTCAGAGATAGGCAAATCCACTACGATTATGTTTCAGGAGGCAAAACCGACTTTCGCTTGGTCAATAGGAACGGTGATGG
GACTCCCACTACGATTATGTTTCAGGAGGACTCCCACTTATCCTTCTAAGTTTACCAGATTTATCCTTGTGTAGGACACAGCCTTATCCTTTCGTAGGTT
GGGAGATTTATCCTTGTCTAGTTACCCAAATTATCCTTCTAAGTTTACAAGATTTATCCTTCACGAGGACCTCTACTTATCCTTCTAAGTTACTAGATTT
ATCCTTTTGTAGGACACAGACTTATCCTTGGGTTGGTTGGCAGATTTATCCTTCCTTAGTGACCCGAATTATCCTTCGTCGACAGAGTTGGAAGATTACT
ATATTTATCCTTCTGCAGTCATTGAAATTATCCTTCTGTACGACTCCAACTTATCCTTCTGTAGGACTCCCACTTATTCCTTTCCTAGCACACAGACTTA
TCCTTGCGTAGATTATTAGATTTAGCCTTCTGCAGTGGCCCGAATTATCCTTCTTCGTCATAGTTGGAAATTTACTACGATTATCTTTCAGGAGGACTCC
CACTTATCCTTCTAAGTTACTAGATTTATCCTTGTGTAGGACACAGCCTTATCCTTCCGTAGGTTGGGAGATTTATCCTTGTCTAGTTACCCGGATTATC
CTTCTAAGTTTACAAGAGTTATCCTTCACCAGGACTTCCACTTATCCTTCTAAGTTACTACATTTATCCTTGTGTAGGACACAGACTTATCCTTCCGTAG
GTTGGGAGATTTATCCTTCTCTAGTTACCCAGATTATCCTTCTAAGTTTACAAGAGTTATCCTTCACCAGGACCTCCACTTATCCTTCTAAGTTACTAGA
TTTATCCTTGTGTAGGACACAGACTTATCCTTCCGTAGGTTGGGAGATTTATCCTTGTCTAGTTACCCAGATTATCCTTCTAAGTTTACAAGAGTTGTCC
TTCACCAGGACCTCCACTTATCCTTCTAAGTTACTAGATTTATCCTTGTGTAGGACACAGACTTATCCTTCCGTAGGTTGGGAGATTTATCCTTGTCTAG
TTACCCAGATTATCCTTCTAAGTTTACAAGAGTTATCCTTCACTGTCACACCCTAAAAATTCAAAATATATAAATTGTTGTTTAAATGGAATTTTTAGAA
TTTATTTTAAAAGCCTAGAAGAGAAGATCTAATTTTAATTAATAAATTCCAATATAAAATGGGGCCATATAAAATTTTATTAAATACTTTGCTTAATTCT
ATAATTCCTAGATTTTTCTGGGATTTATTTTAGCTAAGGAAGTATTTTTAATAAATGGAATTGCATTTCATAAATAATTTAAATTGAAAAGGTTTTAAAA
AGTCTCTTTTGGCTTTGGGCCGAAAGTCGGCCCA
"""

    if request.method == "POST":
        action = request.POST.get("action", "submit")

        fasta_text = request.POST.get("sequence", "").strip()
        match = request.POST.get("match", "2").strip() or "2"
        mismatch = request.POST.get("mismatch", "3").strip() or "3"
        delta = request.POST.get("delta", "5").strip() or "5"
        pm = request.POST.get("pm", "80").strip() or "80"
        pi = request.POST.get("pi", "10").strip() or "10"
        minscore = request.POST.get("minscore", "40").strip() or "40"
        maxlength = request.POST.get("maxlength", "100000").strip() or "100000"
        maxloop = request.POST.get("maxloop", "50000").strip() or "50000"
        flanklen = request.POST.get("flanklen", "200").strip() or "200"
        min_arm_len = request.POST.get("min_arm_len", "400").strip() or "400"

        uploaded_file = request.FILES.get("fasta_file")

        if action == "example":
            fasta_text = example_fasta

        elif action == "reset":
            fasta_text = ""
            results = []
            fasta_map = {}
            align_map = {}
            error_message = None
            message = None
            debug_log = None
            debug_stderr = None
            debug_cmd = None
            debug_files = None
            debug_returncode = None
            warning_message = None

        elif action == "submit":
            try:
                if uploaded_file:
                    fasta_to_use = uploaded_file.read().decode("utf-8", errors="ignore").strip()
                    fasta_text = fasta_to_use
                else:
                    fasta_to_use = fasta_text
                #logger.info(fasta_to_use)
                irf_result = run_irf(
                    fasta_text=fasta_to_use,
                    irf_executable=settings.IRF_EXECUTABLE,
                    match=int(match),
                    mismatch=int(mismatch),
                    delta=int(delta),
                    pm=int(pm),
                    pi=int(pi),
                    minscore=int(minscore),
                    maxlength=int(maxlength),
                    maxloop=int(maxloop),
                    flanklen=int(flanklen),
                    #min_arm_len=0,
                    min_arm_len=int(min_arm_len),   # 先调试用，确认能出原始结果；稳定后可改回 400
                )
                #logger.info(irf_result)
                
                results = irf_result.get("table", [])
                fasta_map = irf_result.get("fasta", {})
                align_map = irf_result.get("align", {})

                debug_log = irf_result.get("log")
                debug_stderr = irf_result.get("stderr")
                debug_cmd = irf_result.get("cmd")
                debug_files = irf_result.get("tmp_files")
                debug_returncode = irf_result.get("returncode")
                warning_message = irf_result.get("warning")

                raw_count = len(irf_result.get("table_all", []))
                final_count = len(results)

                if final_count == 0:
                    if raw_count > 0:
                        message = (
                            f"IRF 已检测到 {raw_count} 个候选结果，但当前展示结果为 0。"
                            f"现在是调试模式，请检查 dat 解析、html 解析和前端展示。"
                        )
                    else:
                        message = "IRF 已运行，但没有检测到候选倒置重复。"

            except Exception as e:
                error_message = str(e)
    
    return render(request, "lir/annotate.html", {
        "results": results,
        "fasta_map": fasta_map,
        "align_map": align_map,
        "error_message": error_message,
        "message": message,
        "warning_message": warning_message,
        "debug_log": debug_log,
        "debug_stderr": debug_stderr,
        "debug_cmd": debug_cmd,
        "debug_files": debug_files,
        "debug_returncode": debug_returncode,
        "fasta_text": fasta_text,
        "match": match,
        "mismatch": mismatch,
        "delta": delta,
        "pm": pm,
        "pi": pi,
        "minscore": minscore,
        "maxlength": maxlength,
        "maxloop": maxloop,
        "flanklen": flanklen,
    })